-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 29-Nov-13 12:15:32
-- Path: /home/tqiu/Desktop/epo3/LUT/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Piece_lut IS

  SIGNAL n79: STD_LOGIC;
  SIGNAL n68: STD_LOGIC;
  SIGNAL n69: STD_LOGIC;
  SIGNAL n70: STD_LOGIC;
  SIGNAL n62: STD_LOGIC;
  SIGNAL n56: STD_LOGIC;
  SIGNAL n58: STD_LOGIC;
  SIGNAL n80: STD_LOGIC;
  SIGNAL n72: STD_LOGIC;
  SIGNAL n71: STD_LOGIC;
  SIGNAL n73: STD_LOGIC;
  SIGNAL n78: STD_LOGIC;
  SIGNAL n63: STD_LOGIC;
  SIGNAL n64: STD_LOGIC;
  SIGNAL n48: STD_LOGIC;
  SIGNAL n66: STD_LOGIC;
  SIGNAL n65: STD_LOGIC;
  SIGNAL next_state_2_port: STD_LOGIC;
  SIGNAL n49: STD_LOGIC;
  SIGNAL n50: STD_LOGIC;
  SIGNAL n47: STD_LOGIC;
  SIGNAL n67: STD_LOGIC;
  SIGNAL n55: STD_LOGIC;
  SIGNAL n54: STD_LOGIC;
  SIGNAL next_state_0_port: STD_LOGIC;
  SIGNAL next_state_1_port: STD_LOGIC;
  SIGNAL n61: STD_LOGIC;
  SIGNAL n53: STD_LOGIC;
  SIGNAL n57: STD_LOGIC;
  SIGNAL state_2_port: STD_LOGIC;
  SIGNAL n52: STD_LOGIC;
  SIGNAL n51: STD_LOGIC;
  SIGNAL n59: STD_LOGIC;
  SIGNAL n74: STD_LOGIC;
  SIGNAL n76: STD_LOGIC;
  SIGNAL n75: STD_LOGIC;
  SIGNAL state_0_port: STD_LOGIC;
  SIGNAL n77: STD_LOGIC;
  SIGNAL n60: STD_LOGIC;
  SIGNAL state_1_port: STD_LOGIC;

  SIGNAL mask_int: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL ready_int: STD_LOGIC;
  SIGNAL error_side_int: STD_LOGIC;
  SIGNAL error_bot_int: STD_LOGIC;
  SIGNAL rom_addr_int: STD_LOGIC_VECTOR(6 DOWNTO 0);

BEGIN

  mask <= mask_int;
  ready <= ready_int;
  error_side <= error_side_int;
  error_bot <= error_bot_int;
  rom_addr <= rom_addr_int;

  rom_addr_int(0) <= mask_select(0);
  rom_addr_int(1) <= mask_select(1);
  rom_addr_int(2) <= rot(0);
  rom_addr_int(3) <= rot(1);
  rom_addr_int(4) <= piece_type(0);
  rom_addr_int(5) <= piece_type(1);
  rom_addr_int(6) <= piece_type(2);
  mask_int(7) <= next_piece;

  U72: na210 PORT MAP (n76, n77, n60);
  U50: na210 PORT MAP (x(2), n60, n59);
  U44: na210 PORT MAP (state_0_port, n52, n54);
  U45: na210 PORT MAP (n53, n55, next_state_0_port);
  U43: na210 PORT MAP (n53, n54, next_state_1_port);
  U75: na210 PORT MAP (rom_data(1), x(1), n76);
  U41: na210 PORT MAP (state_0_port, n50, n49);
  U58: na210 PORT MAP (rom_data(0), x(0), n66);
  U65: na210 PORT MAP (rom_data(2), y(0), n72);
  U82: na210 PORT MAP (state_1_port, n57, n78);
  U52: na210 PORT MAP (n48, n62, n61);
  U46: na210 PORT MAP (n56, n57, n55);
  U47: na210 PORT MAP (n47, n58, n56);
  U48: na210 PORT MAP (start, n51, n58);
  U78: na210 PORT MAP (n79, n80, n70);
  U81: na210 PORT MAP (rom_data(3), y(1), n79);
  U61: na210 PORT MAP (y(2), n70, n69);
  U67: ex210 PORT MAP (n60, x(2), mask_int(2));
  U74: ex210 PORT MAP (rom_data(1), x(1), n67);
  U42: ex210 PORT MAP (n51, n52, n50);
  U57: ex210 PORT MAP (n66, n67, n65);
  U68: ex210 PORT MAP (x(0), rom_data(0), mask_int(0));
  U64: ex210 PORT MAP (n72, n73, n71);
  U66: ex210 PORT MAP (y(0), rom_data(2), mask_int(3));
  U80: ex210 PORT MAP (rom_data(3), y(1), n73);
  U62: ex210 PORT MAP (n70, y(2), mask_int(5));
  U60: ex210 PORT MAP (y(3), n69, n68);
  U71: na310 PORT MAP (n57, n52, n60, n74);
  U49: na310 PORT MAP (n59, n52, state_2_port, n47);
  U73: na310 PORT MAP (rom_data(0), n67, x(0), n77);
  U79: na310 PORT MAP (rom_data(2), n73, y(0), n80);
  U54: na310 PORT MAP (n63, n57, n64, n48);
  U40: na310 PORT MAP (n47, n48, n49, next_state_2_port);
  U53: na310 PORT MAP (n57, n51, state_1_port, n62);
  U77: na310 PORT MAP (y(2), n70, y(3), n63);
  U69: no310 PORT MAP (n74, n51, n75, error_side_int);
  U83: no310 PORT MAP (n57, n52, n51, ready_int);
  U76: no310 PORT MAP (n78, n51, n63, error_bot_int);
  U70: iv110 PORT MAP (x(2), n75);
  U51: iv110 PORT MAP (n61, n53);
  U86: iv110 PORT MAP (state_0_port, n57);
  U84: iv110 PORT MAP (state_2_port, n51);
  U56: iv110 PORT MAP (n65, mask_int(1));
  U63: iv110 PORT MAP (n71, mask_int(4));
  U85: iv110 PORT MAP (state_1_port, n52);
  U59: iv110 PORT MAP (n68, mask_int(6));
  state_reg_0_inst: dfr11 PORT MAP (next_state_0_port, rst, clk, state_0_port);
  state_reg_1_inst: dfr11 PORT MAP (next_state_1_port, rst, clk, state_1_port);
  state_reg_2_inst: dfr11 PORT MAP (next_state_2_port, rst, clk, state_2_port);
  U55: no210 PORT MAP (n52, n51, n64);

END extracted;



