-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 30-Nov-13 13:33:27
-- Path: /home/epo3-user/Desktop/epo3/LUT/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Piece_lut IS

  SIGNAL n52: STD_LOGIC;
  SIGNAL n48: STD_LOGIC;
  SIGNAL n77: STD_LOGIC;
  SIGNAL n76: STD_LOGIC;
  SIGNAL lut_next_state_2_port: STD_LOGIC;
  SIGNAL n71: STD_LOGIC;
  SIGNAL n49: STD_LOGIC;
  SIGNAL n72: STD_LOGIC;
  SIGNAL n62: STD_LOGIC;
  SIGNAL n61: STD_LOGIC;
  SIGNAL n50: STD_LOGIC;
  SIGNAL n47: STD_LOGIC;
  SIGNAL n68: STD_LOGIC;
  SIGNAL lut_state_2_port: STD_LOGIC;
  SIGNAL n69: STD_LOGIC;
  SIGNAL lut_next_state_1_port: STD_LOGIC;
  SIGNAL n59: STD_LOGIC;
  SIGNAL n56: STD_LOGIC;
  SIGNAL n58: STD_LOGIC;
  SIGNAL lut_next_state_0_port: STD_LOGIC;
  SIGNAL lut_state_0_port: STD_LOGIC;
  SIGNAL n80: STD_LOGIC;
  SIGNAL n70: STD_LOGIC;
  SIGNAL n57: STD_LOGIC;
  SIGNAL n79: STD_LOGIC;
  SIGNAL n53: STD_LOGIC;
  SIGNAL n73: STD_LOGIC;
  SIGNAL n51: STD_LOGIC;
  SIGNAL n67: STD_LOGIC;
  SIGNAL n65: STD_LOGIC;
  SIGNAL n64: STD_LOGIC;
  SIGNAL n66: STD_LOGIC;
  SIGNAL lut_state_1_port: STD_LOGIC;
  SIGNAL n60: STD_LOGIC;
  SIGNAL n55: STD_LOGIC;
  SIGNAL n54: STD_LOGIC;
  SIGNAL n78: STD_LOGIC;
  SIGNAL n63: STD_LOGIC;
  SIGNAL n75: STD_LOGIC;
  SIGNAL n74: STD_LOGIC;

  SIGNAL lut_mask_int: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL lut_ready_int: STD_LOGIC;
  SIGNAL lut_error_side_int: STD_LOGIC;
  SIGNAL lut_error_bot_int: STD_LOGIC;
  SIGNAL lut_rom_addr_int: STD_LOGIC_VECTOR(6 DOWNTO 0);

BEGIN

  lut_mask <= lut_mask_int;
  lut_ready <= lut_ready_int;
  lut_error_side <= lut_error_side_int;
  lut_error_bot <= lut_error_bot_int;
  lut_rom_addr <= lut_rom_addr_int;

  lut_rom_addr_int(0) <= lut_mask_select(0);
  lut_rom_addr_int(1) <= lut_mask_select(1);
  lut_rom_addr_int(2) <= lut_rot(0);
  lut_rom_addr_int(3) <= lut_rot(1);
  lut_rom_addr_int(4) <= lut_piece_type(0);
  lut_rom_addr_int(5) <= lut_piece_type(1);
  lut_rom_addr_int(6) <= lut_piece_type(2);
  lut_mask_int(7) <= lut_next_piece;

  U71: na310 PORT MAP (n60, n55, n63, n74);
  U56: na310 PORT MAP (n60, n54, lut_state_1_port, n65);
  U57: na310 PORT MAP (n66, n60, n67, n51);
  U77: na310 PORT MAP (lut_y(2), n70, lut_y(3), n66);
  U52: na310 PORT MAP (n62, n55, lut_state_2_port, n50);
  U79: na310 PORT MAP (lut_rom_data(2), n73, lut_y(0), n80);
  U43: na310 PORT MAP (n50, n51, n52, lut_next_state_2_port);
  U73: na310 PORT MAP (lut_rom_data(0), n49, lut_x(0), n77);
  U69: no310 PORT MAP (n74, n54, n75, lut_error_side_int);
  U76: no310 PORT MAP (n78, n54, n66, lut_error_bot_int);
  U83: no310 PORT MAP (n60, n55, n54, lut_ready_int);
  U70: iv110 PORT MAP (lut_x(2), n75);
  U85: iv110 PORT MAP (lut_state_1_port, n55);
  U86: iv110 PORT MAP (lut_state_0_port, n60);
  U54: iv110 PORT MAP (n64, n56);
  U40: iv110 PORT MAP (n47, lut_mask_int(1));
  U59: iv110 PORT MAP (n68, lut_mask_int(6));
  U84: iv110 PORT MAP (lut_state_2_port, n54);
  U63: iv110 PORT MAP (n71, lut_mask_int(4));
  U82: na210 PORT MAP (lut_state_1_port, n60, n78);
  U47: na210 PORT MAP (lut_state_0_port, n55, n57);
  U81: na210 PORT MAP (lut_rom_data(3), lut_y(1), n79);
  U78: na210 PORT MAP (n79, n80, n70);
  U55: na210 PORT MAP (n51, n65, n64);
  U49: na210 PORT MAP (n59, n60, n58);
  U48: na210 PORT MAP (n56, n58, lut_next_state_0_port);
  U46: na210 PORT MAP (n56, n57, lut_next_state_1_port);
  U61: na210 PORT MAP (lut_y(2), n70, n69);
  U53: na210 PORT MAP (lut_x(2), n63, n62);
  U51: na210 PORT MAP (lut_start, n54, n61);
  U50: na210 PORT MAP (n50, n61, n59);
  U75: na210 PORT MAP (lut_rom_data(1), lut_x(1), n76);
  U72: na210 PORT MAP (n76, n77, n63);
  U65: na210 PORT MAP (lut_rom_data(2), lut_y(0), n72);
  U44: na210 PORT MAP (lut_state_0_port, n53, n52);
  U42: na210 PORT MAP (lut_rom_data(0), lut_x(0), n48);
  U80: ex210 PORT MAP (lut_rom_data(3), lut_y(1), n73);
  U45: ex210 PORT MAP (n54, n55, n53);
  U62: ex210 PORT MAP (n70, lut_y(2), lut_mask_int(5));
  U60: ex210 PORT MAP (lut_y(3), n69, n68);
  U67: ex210 PORT MAP (n63, lut_x(2), lut_mask_int(2));
  U74: ex210 PORT MAP (lut_rom_data(1), lut_x(1), n49);
  U64: ex210 PORT MAP (n72, n73, n71);
  U66: ex210 PORT MAP (lut_y(0), lut_rom_data(2), lut_mask_int(3));
  U41: ex210 PORT MAP (n48, n49, n47);
  U68: ex210 PORT MAP (lut_x(0), lut_rom_data(0), lut_mask_int(0));
  U58: no210 PORT MAP (n55, n54, n67);
  lut_state_reg_2_inst: dfr11 PORT MAP (lut_next_state_2_port, lut_rst, lut_clk, lut_state_2_port);
  lut_state_reg_1_inst: dfr11 PORT MAP (lut_next_state_1_port, lut_rst, lut_clk, lut_state_1_port);
  lut_state_reg_0_inst: dfr11 PORT MAP (lut_next_state_0_port, lut_rst, lut_clk, lut_state_0_port);

END extracted;



