-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 3-Dec-13 12:12:42
-- Path: /home/tqiu/Desktop/epo3/LUT/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Piece_lut IS

  SIGNAL n73: STD_LOGIC;
  SIGNAL n85: STD_LOGIC;
  SIGNAL n75: STD_LOGIC;
  SIGNAL n76: STD_LOGIC;
  SIGNAL n71: STD_LOGIC;
  SIGNAL n70: STD_LOGIC;
  SIGNAL n72: STD_LOGIC;
  SIGNAL n86: STD_LOGIC;
  SIGNAL n84: STD_LOGIC;
  SIGNAL n83: STD_LOGIC;
  SIGNAL n82: STD_LOGIC;
  SIGNAL n65: STD_LOGIC;
  SIGNAL n60: STD_LOGIC;
  SIGNAL n61: STD_LOGIC;
  SIGNAL n56: STD_LOGIC;
  SIGNAL n57: STD_LOGIC;
  SIGNAL n54: STD_LOGIC;
  SIGNAL next_state_0_port: STD_LOGIC;
  SIGNAL next_state_1_port: STD_LOGIC;
  SIGNAL next_state_2_port: STD_LOGIC;
  SIGNAL n66: STD_LOGIC;
  SIGNAL n55: STD_LOGIC;
  SIGNAL n68: STD_LOGIC;
  SIGNAL n62: STD_LOGIC;
  SIGNAL n67: STD_LOGIC;
  SIGNAL n69: STD_LOGIC;
  SIGNAL next_overflow: STD_LOGIC;
  SIGNAL n63: STD_LOGIC;
  SIGNAL n64: STD_LOGIC;
  SIGNAL n58: STD_LOGIC;
  SIGNAL n59: STD_LOGIC;
  SIGNAL state_0_port: STD_LOGIC;
  SIGNAL state_1_port: STD_LOGIC;
  SIGNAL state_2_port: STD_LOGIC;
  SIGNAL n74: STD_LOGIC;
  SIGNAL n81: STD_LOGIC;
  SIGNAL n77: STD_LOGIC;
  SIGNAL n78: STD_LOGIC;
  SIGNAL n80: STD_LOGIC;
  SIGNAL n79: STD_LOGIC;

  SIGNAL mask_int: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL ready_int: STD_LOGIC;
  SIGNAL overflow_int: STD_LOGIC;
  SIGNAL rom_addr_int: STD_LOGIC_VECTOR(6 DOWNTO 0);

BEGIN

  mask <= mask_int;
  ready <= ready_int;
  overflow <= overflow_int;
  rom_addr <= rom_addr_int;

  rom_addr_int(0) <= mask_select(0);
  rom_addr_int(1) <= mask_select(1);
  rom_addr_int(2) <= rot(0);
  rom_addr_int(3) <= rot(1);
  rom_addr_int(4) <= piece_type(0);
  rom_addr_int(5) <= piece_type(1);
  rom_addr_int(6) <= piece_type(2);
  mask_int(7) <= next_piece;

  U78: ex210 PORT MAP (rom_data(3), y(1), n79);
  U77: ex210 PORT MAP (n80, n79, mask_int(4));
  U81: ex210 PORT MAP (y(0), rom_data(2), mask_int(3));
  U90: ex210 PORT MAP (x(0), rom_data(0), mask_int(0));
  U52: ex210 PORT MAP (n61, state_1_port, n60);
  U82: ex210 PORT MAP (n64, x(2), mask_int(2));
  U87: ex210 PORT MAP (rom_data(1), x(1), n84);
  U70: ex210 PORT MAP (n75, n76, mask_int(6));
  U86: ex210 PORT MAP (n85, n84, mask_int(1));
  U73: ex210 PORT MAP (n74, y(2), mask_int(5));
  U76: na210 PORT MAP (rom_data(3), y(1), n77);
  U74: na210 PORT MAP (n77, n78, n74);
  U80: na210 PORT MAP (rom_data(2), y(0), n81);
  U69: na210 PORT MAP (overflow_int, ready_int, n68);
  U61: na210 PORT MAP (n68, n69, next_overflow);
  U55: na210 PORT MAP (n55, n65, next_state_0_port);
  U48: na210 PORT MAP (n54, n55, next_state_2_port);
  U56: na210 PORT MAP (state_1_port, n61, n65);
  U50: na210 PORT MAP (state_1_port, state_0_port, n56);
  U62: na210 PORT MAP (n70, n63, n69);
  U89: na210 PORT MAP (rom_data(0), x(0), n86);
  U68: na210 PORT MAP (n64, x(2), n72);
  U85: na210 PORT MAP (rom_data(1), x(1), n82);
  U83: na210 PORT MAP (n82, n83, n64);
  U71: na210 PORT MAP (y(2), n74, n76);
  U79: iv110 PORT MAP (n81, n80);
  U91: iv110 PORT MAP (n67, ready_int);
  U53: iv110 PORT MAP (n62, n59);
  U64: iv110 PORT MAP (state_2_port, n57);
  U57: iv110 PORT MAP (state_0_port, n61);
  U65: iv110 PORT MAP (n71, n70);
  U88: iv110 PORT MAP (n86, n85);
  U72: iv110 PORT MAP (y(3), n75);
  U75: na310 PORT MAP (rom_data(2), n79, y(0), n78);
  U54: na310 PORT MAP (n63, n64, x(2), n58);
  U92: na310 PORT MAP (state_0_port, state_2_port, state_1_port, n67);
  U51: na310 PORT MAP (n58, n59, n60, next_state_1_port);
  U84: na310 PORT MAP (rom_data(0), n84, x(0), n83);
  U67: na310 PORT MAP (y(3), n74, y(2), n73);
  overflow1_reg: dfr11 PORT MAP (next_overflow, rst, clk, overflow_int);
  state_reg_0_inst: dfr11 PORT MAP (next_state_0_port, rst, clk, state_0_port);
  state_reg_1_inst: dfr11 PORT MAP (next_state_1_port, rst, clk, state_1_port);
  state_reg_2_inst: dfr11 PORT MAP (next_state_2_port, rst, clk, state_2_port);
  U59: no210 PORT MAP (n66, n67, n62);
  U58: no210 PORT MAP (n62, n63, n55);
  U60: no210 PORT MAP (draw_start, check_start, n66);
  U63: no210 PORT MAP (n57, state_0_port, n63);
  U49: mu111 PORT MAP (state_1_port, n56, n57, n54);
  U66: mu111 PORT MAP (n72, n73, state_1_port, n71);

END extracted;



