-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 2-Dec-13 20:15:43
-- Path: /home/epo3-user/vhdl/draw_score_2/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Draw_score IS

  SIGNAL n74: STD_LOGIC;
  SIGNAL n36: STD_LOGIC;
  SIGNAL n77: STD_LOGIC;
  SIGNAL new_state_0_port: STD_LOGIC;
  SIGNAL n69: STD_LOGIC;
  SIGNAL n66: STD_LOGIC;
  SIGNAL n64: STD_LOGIC;
  SIGNAL n68: STD_LOGIC;
  SIGNAL n71: STD_LOGIC;
  SIGNAL n79: STD_LOGIC;
  SIGNAL n57: STD_LOGIC;
  SIGNAL n59: STD_LOGIC;
  SIGNAL n63: STD_LOGIC;
  SIGNAL n49: STD_LOGIC;
  SIGNAL n76: STD_LOGIC;
  SIGNAL i_1_port: STD_LOGIC;
  SIGNAL n70: STD_LOGIC;
  SIGNAL n48: STD_LOGIC;
  SIGNAL n56: STD_LOGIC;
  SIGNAL n67: STD_LOGIC;
  SIGNAL n75: STD_LOGIC;
  SIGNAL n51: STD_LOGIC;
  SIGNAL i_0_port: STD_LOGIC;
  SIGNAL n78: STD_LOGIC;
  SIGNAL n52: STD_LOGIC;
  SIGNAL next_i_1_port: STD_LOGIC;
  SIGNAL n50: STD_LOGIC;
  SIGNAL n53: STD_LOGIC;
  SIGNAL n58: STD_LOGIC;
  SIGNAL i_2_port: STD_LOGIC;
  SIGNAL n72: STD_LOGIC;
  SIGNAL n73: STD_LOGIC;
  SIGNAL state_1_port: STD_LOGIC;
  SIGNAL n61: STD_LOGIC;
  SIGNAL n54: STD_LOGIC;
  SIGNAL n60: STD_LOGIC;
  SIGNAL n55: STD_LOGIC;
  SIGNAL new_state_1_port: STD_LOGIC;
  SIGNAL n62: STD_LOGIC;
  SIGNAL n65: STD_LOGIC;
  SIGNAL state_0_port: STD_LOGIC;
  SIGNAL n47: STD_LOGIC;
  SIGNAL next_i_2_port: STD_LOGIC;

  SIGNAL ds_ready_int: STD_LOGIC;
  SIGNAL ds_write_int: STD_LOGIC;
  SIGNAL ds_addr_int: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL ds_data_out_int: STD_LOGIC;

  SIGNAL vss: STD_LOGIC;
  SIGNAL vdd: STD_LOGIC;
BEGIN
  vdd <= '1';
  vss <= '0';

  ds_ready <= ds_ready_int;
  ds_write <= ds_write_int;
  ds_addr <= ds_addr_int;
  ds_data_out <= ds_data_out_int;


  ds_addr_tri_7_inst: tinv10 PORT MAP (vss, state_0_port, ds_addr_int(7));
  ds_addr_tri_6_inst: tinv10 PORT MAP (vdd, state_0_port, ds_addr_int(6));
  ds_addr_tri_2_inst: tinv10 PORT MAP (i_2_port, state_0_port, ds_addr_int(2));
  ds_addr_tri_4_inst: tinv10 PORT MAP (vss, state_0_port, ds_addr_int(4));
  ds_addr_tri_5_inst: tinv10 PORT MAP (vdd, state_0_port, ds_addr_int(5));
  ds_addr_tri_0_inst: tinv10 PORT MAP (i_0_port, state_0_port, ds_addr_int(0));
  ds_addr_tri_1_inst: tinv10 PORT MAP (i_1_port, state_0_port, ds_addr_int(1));
  ds_data_out_tri: tinv10 PORT MAP (n36, state_0_port, ds_data_out_int);
  ds_addr_tri_3_inst: tinv10 PORT MAP (vdd, state_0_port, ds_addr_int(3));
  U53: iv110 PORT MAP (n47, next_i_2_port);
  U92: iv110 PORT MAP (state_1_port, n62);
  U67: iv110 PORT MAP (state_0_port, n61);
  U88: iv110 PORT MAP (i_0_port, n78);
  U81: iv110 PORT MAP (n70, n53);
  U89: iv110 PORT MAP (n60, ds_write_int);
  U61: iv110 PORT MAP (n56, n50);
  U69: iv110 PORT MAP (i_2_port, n63);
  U85: iv110 PORT MAP (n77, n76);
  U83: iv110 PORT MAP (i_1_port, n74);
  U71: iv110 PORT MAP (n64, n36);
  U66: na310 PORT MAP (n61, n62, ds_draw, n58);
  U60: na310 PORT MAP (ds_write_int, n50, i_2_port, n55);
  U63: na310 PORT MAP (n57, n58, n49, new_state_0_port);
  U80: na210 PORT MAP (ds_input(1), n53, n73);
  U79: na210 PORT MAP (n72, n73, n65);
  U62: na210 PORT MAP (ds_draw, ds_ready_int, n54);
  U59: na210 PORT MAP (n54, n55, new_state_1_port);
  U90: na210 PORT MAP (state_0_port, n62, n60);
  U87: na210 PORT MAP (ds_input(0), n78, n75);
  U57: na210 PORT MAP (n53, ds_write_int, n52);
  U56: na210 PORT MAP (n51, n52, next_i_1_port);
  U55: na210 PORT MAP (n50, ds_write_int, n48);
  U58: na210 PORT MAP (n79, i_1_port, n51);
  U78: na210 PORT MAP (i_1_port, i_0_port, n56);
  U68: na210 PORT MAP (ds_write_int, n63, n57);
  U82: na210 PORT MAP (i_0_port, n74, n70);
  U91: no210 PORT MAP (n62, state_0_port, ds_ready_int);
  U77: no210 PORT MAP (ds_input(7), n56, n67);
  U70: no210 PORT MAP (n60, i_0_port, n79);
  U64: no210 PORT MAP (n79, n59, n49);
  U65: no210 PORT MAP (n60, i_1_port, n59);
  U75: no210 PORT MAP (i_0_port, n71, n68);
  U74: no210 PORT MAP (ds_input(5), n70, n69);
  U84: mu111 PORT MAP (n75, n76, i_1_port, n72);
  U54: mu111 PORT MAP (n48, n49, i_2_port, n47);
  U76: mu111 PORT MAP (ds_input(4), ds_input(6), i_1_port, n71);
  U72: mu111 PORT MAP (n65, n66, i_2_port, n64);
  U86: mu111 PORT MAP (ds_input(2), ds_input(3), i_0_port, n77);
  U73: no310 PORT MAP (n67, n68, n69, n66);
  state_reg_0_inst: dfr11 PORT MAP (new_state_0_port, ds_rst, ds_clk, state_0_port);
  i_reg_1_inst: dfr11 PORT MAP (next_i_1_port, ds_rst, ds_clk, i_1_port);
  i_reg_2_inst: dfr11 PORT MAP (next_i_2_port, ds_rst, ds_clk, i_2_port);
  i_reg_0_inst: dfr11 PORT MAP (n79, ds_rst, ds_clk, i_0_port);
  state_reg_1_inst: dfr11 PORT MAP (new_state_1_port, ds_rst, ds_clk, state_1_port);

END extracted;



