Npg

* Generated by: xspice 2.48 07-May-2008
* Date: 13-Dec-13 1:10:59
* Path: /home/epo3-user/Desktop/git/epo3/master/test
* Language: SPICE

* circuit Npg 1 2 3 4 5 6 7 8 9
*
*   1 pbulk        2 nbulk        3 button_seed  4 new_number   5 rst
*   6 vdd          7 output_2_0_0                8 output_2_0_1
*   9 output_2_0_2
*
m1 10 11 0 2 nenh w=23.2u l=1.6u
m2 10 11 6 1 penh w=29.6u l=1.6u
m3 12 13 6 1 penh w=29.6u l=1.6u
m4 12 13 0 2 nenh w=23.2u l=1.6u
m5 14 15 0 2 nenh w=23.2u l=1.6u
m6 14 15 6 1 penh w=29.6u l=1.6u
m7 16 10 0 2 nenh w=23.2u l=1.6u
m8 17 10 6 1 penh w=29.6u l=1.6u
m9 18 12 6 1 penh w=29.6u l=1.6u
m10 19 12 0 2 nenh w=23.2u l=1.6u
m11 20 14 0 2 nenh w=23.2u l=1.6u
m12 21 14 6 1 penh w=29.6u l=1.6u
m13 16 22 0 2 nenh w=23.2u l=1.6u
m14 17 22 16 1 penh w=29.6u l=1.6u
m15 18 8 23 1 penh w=29.6u l=1.6u
m16 19 24 23 2 nenh w=23.2u l=1.6u
m17 20 25 0 2 nenh w=23.2u l=1.6u
m18 21 25 20 1 penh w=29.6u l=1.6u
m19 26 13 23 1 penh w=29.6u l=1.6u
m20 27 13 23 2 nenh w=23.2u l=1.6u
m21 28 29 0 2 nenh w=23.2u l=1.6u
m22 28 29 6 1 penh w=29.6u l=1.6u
m23 26 24 6 1 penh w=29.6u l=1.6u
m24 27 8 0 2 nenh w=23.2u l=1.6u
m25 30 31 0 2 nenh w=23.2u l=1.6u
m26 30 31 6 1 penh w=29.6u l=1.6u
m27 32 28 0 2 nenh w=23.2u l=1.6u
m28 32 28 6 1 penh w=29.6u l=1.6u
m29 24 8 6 1 penh w=29.6u l=1.6u
m30 24 8 0 2 nenh w=23.2u l=1.6u
m31 33 30 0 2 nenh w=23.2u l=1.6u
m32 33 30 6 1 penh w=29.6u l=1.6u
m33 34 28 0 2 nenh w=23.2u l=1.6u
m34 35 29 6 1 penh w=29.6u l=1.6u
m35 36 37 6 1 penh w=29.6u l=1.6u
m36 36 37 0 2 nenh w=23.2u l=1.6u
m37 38 30 0 2 nenh w=23.2u l=1.6u
m38 39 31 6 1 penh w=29.6u l=1.6u
m39 34 16 40 2 nenh w=23.2u l=1.6u
m40 35 16 40 1 penh w=29.6u l=1.6u
m41 41 36 6 1 penh w=29.6u l=1.6u
m42 42 37 0 2 nenh w=23.2u l=1.6u
m43 38 20 43 2 nenh w=23.2u l=1.6u
m44 39 20 43 1 penh w=29.6u l=1.6u
m45 44 32 40 2 nenh w=23.2u l=1.6u
m46 45 28 40 1 penh w=29.6u l=1.6u
m47 41 7 46 1 penh w=29.6u l=1.6u
m48 42 7 46 2 nenh w=23.2u l=1.6u
m49 47 33 43 2 nenh w=23.2u l=1.6u
m50 48 30 43 1 penh w=29.6u l=1.6u
m51 44 49 0 2 nenh w=23.2u l=1.6u
m52 45 49 6 1 penh w=29.6u l=1.6u
m53 50 37 46 1 penh w=29.6u l=1.6u
m54 51 36 46 2 nenh w=23.2u l=1.6u
m55 47 52 0 2 nenh w=23.2u l=1.6u
m56 48 52 6 1 penh w=29.6u l=1.6u
m57 49 40 0 2 nenh w=23.2u l=1.6u
m58 49 40 6 1 penh w=29.6u l=1.6u
m59 50 8 6 1 penh w=29.6u l=1.6u
m60 51 8 0 2 nenh w=23.2u l=1.6u
m61 52 43 0 2 nenh w=23.2u l=1.6u
m62 52 43 6 1 penh w=29.6u l=1.6u
m63 53 46 6 1 penh w=29.6u l=1.6u
m64 53 46 0 2 nenh w=23.2u l=1.6u
m65 54 49 0 2 nenh w=23.2u l=1.6u
m66 55 49 6 1 penh w=29.6u l=1.6u
m67 56 52 0 2 nenh w=23.2u l=1.6u
m68 57 52 6 1 penh w=29.6u l=1.6u
m69 54 32 58 2 nenh w=23.2u l=1.6u
m70 55 28 58 1 penh w=29.6u l=1.6u
m71 13 7 6 1 penh w=29.6u l=1.6u
m72 13 7 0 2 nenh w=23.2u l=1.6u
m73 56 33 59 2 nenh w=23.2u l=1.6u
m74 57 30 59 1 penh w=29.6u l=1.6u
m75 58 28 60 2 nenh w=23.2u l=1.6u
m76 58 32 60 1 penh w=29.6u l=1.6u
m77 59 30 61 2 nenh w=23.2u l=1.6u
m78 59 33 61 1 penh w=29.6u l=1.6u
m79 60 62 0 2 nenh w=23.2u l=1.6u
m80 60 62 6 1 penh w=29.6u l=1.6u
m81 63 37 6 1 penh w=29.6u l=1.6u
m82 63 37 0 2 nenh w=23.2u l=1.6u
m83 61 64 0 2 nenh w=23.2u l=1.6u
m84 61 64 6 1 penh w=29.6u l=1.6u
m85 62 58 0 2 nenh w=23.2u l=1.6u
m86 62 58 6 1 penh w=29.6u l=1.6u
m87 65 63 6 1 penh w=29.6u l=1.6u
m88 66 37 0 2 nenh w=23.2u l=1.6u
m89 64 59 0 2 nenh w=23.2u l=1.6u
m90 64 59 6 1 penh w=29.6u l=1.6u
m91 65 8 67 1 penh w=29.6u l=1.6u
m92 66 8 67 2 nenh w=23.2u l=1.6u
m93 68 60 0 2 nenh w=23.2u l=1.6u
m94 68 60 6 1 penh w=29.6u l=1.6u
m95 69 37 67 1 penh w=29.6u l=1.6u
m96 70 63 67 2 nenh w=23.2u l=1.6u
m97 71 61 0 2 nenh w=23.2u l=1.6u
m98 71 61 6 1 penh w=29.6u l=1.6u
m99 69 9 6 1 penh w=29.6u l=1.6u
m100 70 9 0 2 nenh w=23.2u l=1.6u
m101 72 67 6 1 penh w=29.6u l=1.6u
m102 72 67 0 2 nenh w=23.2u l=1.6u
m103 73 74 0 2 nenh w=23.2u l=1.6u
m104 73 74 6 1 penh w=29.6u l=1.6u
m105 75 76 0 2 nenh w=23.2u l=1.6u
m106 75 76 6 1 penh w=29.6u l=1.6u
m107 77 73 0 2 nenh w=23.2u l=1.6u
m108 78 73 6 1 penh w=29.6u l=1.6u
m109 79 75 0 2 nenh w=23.2u l=1.6u
m110 80 75 6 1 penh w=29.6u l=1.6u
m111 77 81 0 2 nenh w=23.2u l=1.6u
m112 78 81 77 1 penh w=29.6u l=1.6u
m113 82 37 6 1 penh w=29.6u l=1.6u
m114 82 37 0 2 nenh w=23.2u l=1.6u
m115 79 83 0 2 nenh w=23.2u l=1.6u
m116 80 83 79 1 penh w=29.6u l=1.6u
m117 84 82 6 1 penh w=29.6u l=1.6u
m118 85 82 0 2 nenh w=23.2u l=1.6u
m119 86 87 0 2 nenh w=23.2u l=1.6u
m120 86 87 6 1 penh w=29.6u l=1.6u
m121 84 3 88 1 penh w=29.6u l=1.6u
m122 85 89 88 2 nenh w=23.2u l=1.6u
m123 90 91 0 2 nenh w=23.2u l=1.6u
m124 90 91 6 1 penh w=29.6u l=1.6u
m125 92 86 0 2 nenh w=23.2u l=1.6u
m126 92 86 6 1 penh w=29.6u l=1.6u
m127 88 37 93 1 penh w=29.6u l=1.6u
m128 88 37 94 2 nenh w=23.2u l=1.6u
m129 95 90 0 2 nenh w=23.2u l=1.6u
m130 95 90 6 1 penh w=29.6u l=1.6u
m131 93 89 6 1 penh w=29.6u l=1.6u
m132 94 3 0 2 nenh w=23.2u l=1.6u
m133 96 86 0 2 nenh w=23.2u l=1.6u
m134 97 87 6 1 penh w=29.6u l=1.6u
m135 89 3 6 1 penh w=29.6u l=1.6u
m136 89 3 0 2 nenh w=23.2u l=1.6u
m137 98 90 0 2 nenh w=23.2u l=1.6u
m138 99 91 6 1 penh w=29.6u l=1.6u
m139 96 77 100 2 nenh w=23.2u l=1.6u
m140 97 77 100 1 penh w=29.6u l=1.6u
m141 98 79 101 2 nenh w=23.2u l=1.6u
m142 99 79 101 1 penh w=29.6u l=1.6u
m143 102 92 100 2 nenh w=23.2u l=1.6u
m144 103 86 100 1 penh w=29.6u l=1.6u
m145 104 4 6 1 penh w=29.6u l=1.6u
m146 105 4 0 2 nenh w=23.2u l=1.6u
m147 106 95 101 2 nenh w=23.2u l=1.6u
m148 107 90 101 1 penh w=29.6u l=1.6u
m149 102 108 0 2 nenh w=23.2u l=1.6u
m150 103 108 6 1 penh w=29.6u l=1.6u
m151 104 5 105 1 penh w=29.6u l=1.6u
m152 105 5 0 2 nenh w=23.2u l=1.6u
m153 106 109 0 2 nenh w=23.2u l=1.6u
m154 107 109 6 1 penh w=29.6u l=1.6u
m155 108 100 0 2 nenh w=23.2u l=1.6u
m156 108 100 6 1 penh w=29.6u l=1.6u
m157 109 101 0 2 nenh w=23.2u l=1.6u
m158 109 101 6 1 penh w=29.6u l=1.6u
m159 110 105 6 1 penh w=29.6u l=1.6u
m160 110 105 0 2 nenh w=23.2u l=1.6u
m161 111 108 0 2 nenh w=23.2u l=1.6u
m162 112 108 6 1 penh w=29.6u l=1.6u
m163 113 109 0 2 nenh w=23.2u l=1.6u
m164 114 109 6 1 penh w=29.6u l=1.6u
m165 111 92 115 2 nenh w=23.2u l=1.6u
m166 112 86 115 1 penh w=29.6u l=1.6u
m167 116 37 6 1 penh w=29.6u l=1.6u
m168 116 37 0 2 nenh w=23.2u l=1.6u
m169 113 95 117 2 nenh w=23.2u l=1.6u
m170 114 90 117 1 penh w=29.6u l=1.6u
m171 115 86 118 2 nenh w=23.2u l=1.6u
m172 115 92 118 1 penh w=29.6u l=1.6u
m173 119 116 6 1 penh w=29.6u l=1.6u
m174 120 37 0 2 nenh w=23.2u l=1.6u
m175 117 90 121 2 nenh w=23.2u l=1.6u
m176 117 95 121 1 penh w=29.6u l=1.6u
m177 118 122 0 2 nenh w=23.2u l=1.6u
m178 118 122 6 1 penh w=29.6u l=1.6u
m179 119 9 123 1 penh w=29.6u l=1.6u
m180 120 9 123 2 nenh w=23.2u l=1.6u
m181 121 124 0 2 nenh w=23.2u l=1.6u
m182 121 124 6 1 penh w=29.6u l=1.6u
m183 122 115 0 2 nenh w=23.2u l=1.6u
m184 122 115 6 1 penh w=29.6u l=1.6u
m185 125 37 123 1 penh w=29.6u l=1.6u
m186 126 116 123 2 nenh w=23.2u l=1.6u
m187 124 117 0 2 nenh w=23.2u l=1.6u
m188 124 117 6 1 penh w=29.6u l=1.6u
m189 125 23 6 1 penh w=29.6u l=1.6u
m190 126 23 0 2 nenh w=23.2u l=1.6u
m191 127 118 0 2 nenh w=23.2u l=1.6u
m192 127 118 6 1 penh w=29.6u l=1.6u
m193 128 123 6 1 penh w=29.6u l=1.6u
m194 128 123 0 2 nenh w=23.2u l=1.6u
m195 129 121 0 2 nenh w=23.2u l=1.6u
m196 129 121 6 1 penh w=29.6u l=1.6u
*
* namelist Npg
*
*   0 vss          1 pbulk        2 nbulk        3 button_seed  4 new_number
*   5 rst          6 vdd          7 output_2_0_0                8 output_2_0_1
*   9 output_2_0_2               10 7           11 1           12 8
*  13 n5          14 9           15 2           16 51          17 14
*  18 16          19 17          20 54          21 18          22 15
*  23 n4          24 38          25 19          26 28          27 29
*  28 102         29 43          30 104         31 44          32 103
*  33 105         34 49          35 50          36 67          37 shift
*  38 52          39 53          40 74          41 59          42 60
*  43 77          44 65          45 66          46 82          47 68
*  48 69          49 87          50 75          51 76          52 89
*  53 88          54 94          55 95          56 96          57 97
*  58 114         59 115         60 128         61 130         62 120
*  63 129         64 123         65 121         66 122         67 147
*  68 135         69 136         70 137         71 138         72 157
*  73 163         74 156         75 168         76 158         77 211
*  78 173         79 215         80 175         81 174         82 181
*  83 176         84 186         85 187         86 258         87 203
*  88 192         89 212         90 260         91 204         92 259
*  93 197         94 198         95 261         96 209         97 210
*  98 213         99 214        100 233        101 234        102 224
* 103 225        104 226        105 n6         106 227        107 228
* 108 243        109 245        110 244        111 250        112 251
* 113 252        114 253        115 272        116 273        117 274
* 118 287        119 266        120 267        121 289        122 279
* 123 288        124 282        125 280        126 281        127 294
* 128 295        129 296
*
* end Npg

* range: w >= 3u,  3u >= l >= 1.6u
*        |Vd| <= 5.5v,  |Vg| > 1.5v, |Vb| < 5v

* originally we had rsh=55 (nenh) and rsh=75 (penh) but its influence
* can be neglected and it spoils the simulations if we use "ghoti -r"

.model nenh nmos        level=2
+                       ld=0.325u       tox=250e-10     nsub=2e16
+                       vto=0.7         uo=510          uexp=0.22
+                       ucrit=24.3k     delta=0.4       xj=0.4u
+                       vmax=54k        neff=4.0        rsh=0
+                       nfs=0e11        js=2u           cj=130u
+                       cjsw=620p       mj=0.53         mjsw=0.53
+                       pb=0.68v        cgdo=320p       cgso=320p
* end nenh

.model penh pmos        level=2
+                       ld=0.3u         tox=250e-10     nsub=5e16
+                       vto=-1.1        uo=210          uexp=0.33
+                       ucrit=51k       delta=0.4       xj=0.5u
+                       vmax=47k        neff=0.88       rsh=0
+                       nfs=0e11        js=10u          cj=490u
+                       cjsw=590p       mj=0.46         mjsw=0.46
+                       pb=0.78v        cgdo=320p       cgso=320p
* end penh

vpbulk 1 0 5V
rpbulk 1 0 100meg
vnbulk 2 0 0V
rnbulk 2 0 100meg

* vdd ? 0 5V
* rgnd ? 0 1p
* rvss ? 0 1p

