-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 30-Nov-13 19:33:04
-- Path: /home/epo3-user/vhdl/timer/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Timer IS

  SIGNAL new_count_7_port: STD_LOGIC;
  SIGNAL n31: STD_LOGIC;
  SIGNAL new_state_1_port: STD_LOGIC;
  SIGNAL n86: STD_LOGIC;
  SIGNAL n32: STD_LOGIC;
  SIGNAL n82: STD_LOGIC;
  SIGNAL n35: STD_LOGIC;
  SIGNAL n85: STD_LOGIC;
  SIGNAL n84: STD_LOGIC;
  SIGNAL n74: STD_LOGIC;
  SIGNAL count_7_port: STD_LOGIC;
  SIGNAL n37: STD_LOGIC;
  SIGNAL n33: STD_LOGIC;
  SIGNAL new_state_0_port: STD_LOGIC;
  SIGNAL state_0_port: STD_LOGIC;
  SIGNAL n36: STD_LOGIC;
  SIGNAL n75: STD_LOGIC;
  SIGNAL n73: STD_LOGIC;
  SIGNAL count_4_port: STD_LOGIC;
  SIGNAL new_count_2_port: STD_LOGIC;
  SIGNAL n70: STD_LOGIC;
  SIGNAL new_count_1_port: STD_LOGIC;
  SIGNAL n63: STD_LOGIC;
  SIGNAL count_2_port: STD_LOGIC;
  SIGNAL n64: STD_LOGIC;
  SIGNAL count_1_port: STD_LOGIC;
  SIGNAL n83: STD_LOGIC;
  SIGNAL n81: STD_LOGIC;
  SIGNAL n38: STD_LOGIC;
  SIGNAL n77: STD_LOGIC;
  SIGNAL count_6_port: STD_LOGIC;
  SIGNAL n78: STD_LOGIC;
  SIGNAL n39: STD_LOGIC;
  SIGNAL n79: STD_LOGIC;
  SIGNAL n41: STD_LOGIC;
  SIGNAL new_count_6_port: STD_LOGIC;
  SIGNAL n76: STD_LOGIC;
  SIGNAL n40: STD_LOGIC;
  SIGNAL n80: STD_LOGIC;
  SIGNAL new_count_4_port: STD_LOGIC;
  SIGNAL n52: STD_LOGIC;
  SIGNAL n65: STD_LOGIC;
  SIGNAL n71: STD_LOGIC;
  SIGNAL n62: STD_LOGIC;
  SIGNAL n69: STD_LOGIC;
  SIGNAL n67: STD_LOGIC;
  SIGNAL n66: STD_LOGIC;
  SIGNAL n68: STD_LOGIC;
  SIGNAL clk_sig: STD_LOGIC;
  SIGNAL new_count_3_port: STD_LOGIC;
  SIGNAL count_0_port: STD_LOGIC;
  SIGNAL new_count_0_port: STD_LOGIC;
  SIGNAL n42: STD_LOGIC;
  SIGNAL count_3_port: STD_LOGIC;
  SIGNAL n58: STD_LOGIC;
  SIGNAL n55: STD_LOGIC;
  SIGNAL n51: STD_LOGIC;
  SIGNAL n72: STD_LOGIC;
  SIGNAL new_count_5_port: STD_LOGIC;
  SIGNAL n43: STD_LOGIC;
  SIGNAL n45: STD_LOGIC;
  SIGNAL n48: STD_LOGIC;
  SIGNAL count_5_port: STD_LOGIC;
  SIGNAL n47: STD_LOGIC;
  SIGNAL n61: STD_LOGIC;
  SIGNAL n53: STD_LOGIC;
  SIGNAL n34: STD_LOGIC;
  SIGNAL n60: STD_LOGIC;
  SIGNAL n54: STD_LOGIC;
  SIGNAL n56: STD_LOGIC;
  SIGNAL n30: STD_LOGIC;
  SIGNAL n50: STD_LOGIC;
  SIGNAL n46: STD_LOGIC;
  SIGNAL n44: STD_LOGIC;
  SIGNAL n49: STD_LOGIC;
  SIGNAL n59: STD_LOGIC;
  SIGNAL n57: STD_LOGIC;

  SIGNAL timer_done_int: STD_LOGIC;

BEGIN

  timer_done <= timer_done_int;


  U65: no310 PORT MAP (n34, n53, n54, n56);
  U57: no310 PORT MAP (n46, n47, n34, n42);
  U63: no310 PORT MAP (n52, n53, n54, n51);
  U93: no310 PORT MAP (n77, n78, n79, n76);
  U75: no310 PORT MAP (n34, n65, n66, n63);
  U87: no310 PORT MAP (n36, timer_done_int, n73, n72);
  U101: no310 PORT MAP (n82, n83, n84, n75);
  U72: no210 PORT MAP (n54, n34, n60);
  U55: no210 PORT MAP (n44, n45, n43);
  U56: no210 PORT MAP (n34, count_5_port, n45);
  U61: no210 PORT MAP (n46, n34, n48);
  U50: no210 PORT MAP (n40, n41, n39);
  U51: no210 PORT MAP (n34, count_6_port, n41);
  U84: no210 PORT MAP (n65, n34, n70);
  U67: na210 PORT MAP (n50, n53, n58);
  U66: na210 PORT MAP (n57, n58, n55);
  U59: na210 PORT MAP (n30, n49, n44);
  U60: na210 PORT MAP (n50, n46, n49);
  U71: na210 PORT MAP (n50, n54, n61);
  U70: na210 PORT MAP (n30, n61, n59);
  U81: na210 PORT MAP (n30, n71, n69);
  U82: na210 PORT MAP (n50, n65, n71);
  U77: na210 PORT MAP (n50, n66, n68);
  U76: na210 PORT MAP (n67, n68, n62);
  U52: na210 PORT MAP (count_6_port, n42, n38);
  U96: na210 PORT MAP (n80, n81, n77);
  U45: na210 PORT MAP (n33, n34, new_state_0_port);
  U92: na210 PORT MAP (n75, n76, n73);
  U42: na210 PORT MAP (n30, n31, new_state_1_port);
  U44: na210 PORT MAP (timer_start, state_0_port, n32);
  U47: na210 PORT MAP (n36, timer_start, n35);
  U43: na210 PORT MAP (timer_done_int, n32, n31);
  U104: na210 PORT MAP (n85, n86, n82);
  U62: iv110 PORT MAP (n51, n46);
  U83: iv110 PORT MAP (n72, n30);
  U68: iv110 PORT MAP (n59, n57);
  U89: iv110 PORT MAP (n34, n50);
  U108: iv110 PORT MAP (count_5_port, n47);
  U79: iv110 PORT MAP (n69, n67);
  U100: iv110 PORT MAP (count_3_port, n53);
  U54: iv110 PORT MAP (n43, n40);
  U85: iv110 PORT MAP (count_0_port, n65);
  U106: iv110 PORT MAP (count_4_port, n52);
  U98: iv110 PORT MAP (count_2_port, n64);
  U88: iv110 PORT MAP (state_0_port, n36);
  U78: iv110 PORT MAP (count_1_port, n66);
  U91: iv110 PORT MAP (timer_done_int, n74);
  U48: iv110 PORT MAP (n37, new_count_7_port);
  U58: mu111 PORT MAP (n48, n44, count_5_port, new_count_5_port);
  U69: mu111 PORT MAP (n60, n59, count_3_port, new_count_3_port);
  U86: mu111 PORT MAP (n50, n72, count_0_port, new_count_0_port);
  U64: mu111 PORT MAP (n55, n56, n52, new_count_4_port);
  U53: mu111 PORT MAP (n42, n40, count_6_port, new_count_6_port);
  U109: mu111 PORT MAP (timer_vga_clk, timer_clk, timer_rst, clk_sig);
  U74: mu111 PORT MAP (n62, n63, n64, new_count_2_port);
  U80: mu111 PORT MAP (n70, n69, count_1_port, new_count_1_port);
  U49: mu111 PORT MAP (n38, n39, count_7_port, n37);
  count_reg_3_inst: dfr11 PORT MAP (new_count_3_port, timer_rst, clk_sig, count_3_port);
  count_reg_0_inst: dfr11 PORT MAP (new_count_0_port, timer_rst, clk_sig, count_0_port);
  count_reg_5_inst: dfr11 PORT MAP (new_count_5_port, timer_rst, clk_sig, count_5_port);
  count_reg_6_inst: dfr11 PORT MAP (new_count_6_port, timer_rst, clk_sig, count_6_port);
  count_reg_1_inst: dfr11 PORT MAP (new_count_1_port, timer_rst, clk_sig, count_1_port);
  count_reg_4_inst: dfr11 PORT MAP (new_count_4_port, timer_rst, clk_sig, count_4_port);
  count_reg_2_inst: dfr11 PORT MAP (new_count_2_port, timer_rst, clk_sig, count_2_port);
  state_reg_0_inst: dfr11 PORT MAP (new_state_0_port, timer_rst, clk_sig, state_0_port);
  count_reg_7_inst: dfr11 PORT MAP (new_count_7_port, timer_rst, clk_sig, count_7_port);
  state_reg_1_inst: dfr11 PORT MAP (new_state_1_port, timer_rst, clk_sig, timer_done_int);
  U99: ex210 PORT MAP (n53, timer_time(3), n80);
  U97: ex210 PORT MAP (n64, timer_time(2), n81);
  U95: ex210 PORT MAP (timer_time(0), count_0_port, n78);
  U94: ex210 PORT MAP (timer_time(1), count_1_port, n79);
  U103: ex210 PORT MAP (timer_time(6), count_6_port, n83);
  U102: ex210 PORT MAP (timer_time(7), count_7_port, n84);
  U105: ex210 PORT MAP (n52, timer_time(4), n86);
  U46: ex210 PORT MAP (timer_done_int, n35, n33);
  U107: ex210 PORT MAP (n47, timer_time(5), n85);
  U73: na310 PORT MAP (count_1_port, count_0_port, count_2_port, n54);
  U90: na310 PORT MAP (n73, n74, state_0_port, n34);

END extracted;



