-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 26-Nov-13 9:46:49
-- Path: /home/tqiu/Documents/CheckMask/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Checkmask IS

  SIGNAL n8: STD_LOGIC;
  SIGNAL n3: STD_LOGIC;
  SIGNAL n10: STD_LOGIC;
  SIGNAL n5: STD_LOGIC;
  SIGNAL n4: STD_LOGIC;
  SIGNAL n6: STD_LOGIC;
  SIGNAL next_state_1_port: STD_LOGIC;
  SIGNAL n9: STD_LOGIC;
  SIGNAL n7: STD_LOGIC;
  SIGNAL state_1_port: STD_LOGIC;
  SIGNAL n12: STD_LOGIC;
  SIGNAL state_0_port: STD_LOGIC;
  SIGNAL n13: STD_LOGIC;
  SIGNAL next_state_0_port: STD_LOGIC;

  SIGNAL write_int: STD_LOGIC;
  SIGNAL ready_int: STD_LOGIC;
  SIGNAL empty_int: STD_LOGIC;
  SIGNAL ram_out_int: STD_LOGIC_VECTOR(7 DOWNTO 0);

  SIGNAL vss: STD_LOGIC;
BEGIN
  vss <= '0';

  write <= write_int;
  ready <= ready_int;
  empty <= empty_int;
  ram_out <= ram_out_int;

  write_int <= vss;

  U22: iv110 PORT MAP (ram_in(2), n8);
  U28: iv110 PORT MAP (ram_in(0), n10);
  U27: iv110 PORT MAP (ram_in(7), n3);
  U24: iv110 PORT MAP (ram_in(4), n6);
  U25: iv110 PORT MAP (ram_in(5), n5);
  U26: iv110 PORT MAP (ram_in(6), n4);
  U23: iv110 PORT MAP (ram_in(3), n7);
  U21: iv110 PORT MAP (ram_in(1), n9);
  U16: iv110 PORT MAP (n12, ready_int);
  ram_out_tri_2_inst: tinv10 PORT MAP (state_1_port, n8, ram_out_int(2));
  ram_out_tri_4_inst: tinv10 PORT MAP (state_1_port, n6, ram_out_int(4));
  ram_out_tri_7_inst: tinv10 PORT MAP (state_1_port, n3, ram_out_int(7));
  ram_out_tri_0_inst: tinv10 PORT MAP (state_1_port, n10, ram_out_int(0));
  ram_out_tri_5_inst: tinv10 PORT MAP (state_1_port, n5, ram_out_int(5));
  ram_out_tri_6_inst: tinv10 PORT MAP (state_1_port, n4, ram_out_int(6));
  ram_out_tri_3_inst: tinv10 PORT MAP (state_1_port, n7, ram_out_int(3));
  ram_out_tri_1_inst: tinv10 PORT MAP (state_1_port, n9, ram_out_int(1));
  empty_tri: tinv10 PORT MAP (ready_int, data, empty_int);
  state_reg_1_inst: dfr11 PORT MAP (next_state_1_port, reset, clk, state_1_port);
  state_reg_0_inst: dfr11 PORT MAP (next_state_0_port, reset, clk, state_0_port);
  U18: ex210 PORT MAP (state_1_port, state_0_port, next_state_1_port);
  U19: no210 PORT MAP (state_0_port, n13, next_state_0_port);
  U20: no210 PORT MAP (start, state_1_port, n13);
  U17: na210 PORT MAP (state_0_port, state_1_port, n12);

END extracted;



