-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 3-Dec-13 10:12:49
-- Path: /home/rdmiedema/epo3/score/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Log IS

  SIGNAL n15: STD_LOGIC;
  SIGNAL n16: STD_LOGIC;
  SIGNAL n17: STD_LOGIC;
  SIGNAL n18: STD_LOGIC;
  SIGNAL n13: STD_LOGIC;
  SIGNAL n14: STD_LOGIC;
  SIGNAL n19: STD_LOGIC;

  SIGNAL log_out_int: STD_LOGIC_VECTOR(7 DOWNTO 0);

BEGIN

  log_out <= log_out_int;

  log_out_int(7) <= log_in(7);

  U27: na210 PORT MAP (n13, n19, log_out_int(5));
  U24: na210 PORT MAP (n14, n18, log_out_int(3));
  U26: no210 PORT MAP (log_in(4), log_out_int(5), n14);
  U23: no210 PORT MAP (log_in(2), log_out_int(3), n17);
  U21: no210 PORT MAP (log_out_int(2), log_in(1), n16);
  U19: no210 PORT MAP (log_in(0), log_out_int(1), n15);
  U29: no210 PORT MAP (log_in(6), log_in(7), n13);
  U28: iv110 PORT MAP (log_in(5), n19);
  U17: iv110 PORT MAP (n14, log_out_int(4));
  U25: iv110 PORT MAP (log_in(3), n18);
  U22: iv110 PORT MAP (n17, log_out_int(2));
  U18: iv110 PORT MAP (n15, log_out_int(0));
  U20: iv110 PORT MAP (n16, log_out_int(1));
  U16: iv110 PORT MAP (n13, log_out_int(6));

END extracted;



