-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 3-Dec-13 10:32:18
-- Path: /home/rdmiedema/epo3/score/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Log_score IS

  SIGNAL N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8: STD_LOGIC;
  SIGNAL N_9, N_10, N_11, N_12, N_13, N_14, N_15, N_16: STD_LOGIC;
  SIGNAL N_17, N_18, N_19, N_20, N_21, N_22, N_23, N_24: STD_LOGIC;
  SIGNAL N_25, N_26, N_27, N_28, N_29, N_30, N_31, N_32: STD_LOGIC;
  SIGNAL N_33, N_34, N_35, N_36, N_37, N_38, N_39, N_40: STD_LOGIC;
  SIGNAL N_41, N_42: STD_LOGIC;
  SIGNAL score_to_log_6_port: STD_LOGIC;
  SIGNAL score_to_log_0_port: STD_LOGIC;
  SIGNAL score_to_log_1_port: STD_LOGIC;
  SIGNAL score_to_log_2_port: STD_LOGIC;
  SIGNAL score_to_log_3_port: STD_LOGIC;
  SIGNAL score_to_log_4_port: STD_LOGIC;
  SIGNAL score_to_log_5_port: STD_LOGIC;

  SIGNAL output_int: STD_LOGIC_VECTOR(7 DOWNTO 0);

BEGIN

  output <= output_int;


  L1_score_reg_1_inst: dfr11 PORT MAP (N_27, rst, clk, score_to_log_1_port);
  L1_score_reg_6_inst: dfr11 PORT MAP (N_18, rst, clk, score_to_log_6_port);
  L1_score_reg_4_inst: dfr11 PORT MAP (N_7, rst, clk, score_to_log_4_port);
  L1_score_reg_2_inst: dfr11 PORT MAP (N_17, rst, clk, score_to_log_2_port);
  L1_score_reg_0_inst: dfr11 PORT MAP (N_25, rst, clk, score_to_log_0_port);
  L1_score_reg_7_inst: dfr11 PORT MAP (N_2, rst, clk, output_int(7));
  L1_score_reg_5_inst: dfr11 PORT MAP (N_8, rst, clk, score_to_log_5_port);
  L1_score_reg_3_inst: dfr11 PORT MAP (N_1, rst, clk, score_to_log_3_port);
  L1_add_30_aco_U21: ex210 PORT MAP (N_19, score_to_log_2_port, N_20);
  L1_add_30_aco_U20: ex210 PORT MAP (N_22, N_20, N_17);
  L1_add_30_aco_U9: ex210 PORT MAP (score_to_log_6_port, N_21, N_18);
  L1_add_30_aco_U7: ex210 PORT MAP (output_int(7), N_9, N_3);
  L1_add_30_aco_U15: ex210 PORT MAP (score_to_log_3_port, N_4, N_1);
  L1_add_30_aco_U13: ex210 PORT MAP (score_to_log_4_port, N_5, N_6);
  L1_add_30_aco_U29: ex210 PORT MAP (N_30, score_to_log_0_port, N_25);
  L1_add_30_aco_U11: ex210 PORT MAP (N_10, N_12, N_8);
  L1_add_30_aco_U27: ex210 PORT MAP (N_28, score_to_log_1_port, N_29);
  L1_add_30_aco_U26: ex210 PORT MAP (N_33, N_29, N_27);
  L1_add_30_aco_U12: na310 PORT MAP (score_to_log_3_port, N_4, score_to_log_4_port, N_12);
  L2_U27: na210 PORT MAP (N_40, N_42, output_int(5));
  L2_U24: na210 PORT MAP (N_41, N_39, output_int(3));
  L1_add_30_aco_U24: na210 PORT MAP (N_35, N_31, N_32);
  L1_U11: na210 PORT MAP (increase_value(2), increase, N_14);
  L1_add_30_aco_U23: na210 PORT MAP (N_28, N_32, N_23);
  L1_add_30_aco_U22: na210 PORT MAP (N_34, N_23, N_22);
  L1_add_30_aco_U19: na210 PORT MAP (score_to_log_2_port, N_22, N_24);
  L1_add_30_aco_U8: na210 PORT MAP (N_21, score_to_log_6_port, N_9);
  L1_add_30_aco_U17: na210 PORT MAP (N_19, N_16, N_11);
  L1_add_30_aco_U16: na210 PORT MAP (N_24, N_11, N_4);
  L1_add_30_aco_U14: na210 PORT MAP (N_4, score_to_log_3_port, N_5);
  L1_add_30_aco_U28: na210 PORT MAP (N_30, score_to_log_0_port, N_31);
  L1_U15: na210 PORT MAP (increase_value(0), increase, N_26);
  L1_U13: na210 PORT MAP (increase_value(1), increase, N_13);
  L1_add_30_aco_U25: na210 PORT MAP (score_to_log_1_port, N_33, N_34);
  L2_U26: no210 PORT MAP (score_to_log_4_port, output_int(5), N_41);
  L2_U23: no210 PORT MAP (score_to_log_2_port, output_int(3), N_38);
  L2_U21: no210 PORT MAP (output_int(2), score_to_log_1_port, N_37);
  L2_U19: no210 PORT MAP (score_to_log_0_port, output_int(1), N_36);
  L2_U29: no210 PORT MAP (score_to_log_6_port, output_int(7), N_40);
  L1_add_30_aco_U18: no210 PORT MAP (N_22, score_to_log_2_port, N_15);
  L1_add_30_aco_U10: no210 PORT MAP (N_10, N_12, N_21);
  L2_U28: iv110 PORT MAP (score_to_log_5_port, N_42);
  L2_U17: iv110 PORT MAP (N_41, output_int(4));
  L2_U25: iv110 PORT MAP (score_to_log_3_port, N_39);
  L2_U22: iv110 PORT MAP (N_38, output_int(2));
  L2_U18: iv110 PORT MAP (N_36, output_int(0));
  L2_U20: iv110 PORT MAP (N_37, output_int(1));
  L2_U16: iv110 PORT MAP (N_40, output_int(6));
  L1_U10: iv110 PORT MAP (N_14, N_19);
  L1_add_30_aco_U6: iv110 PORT MAP (score_to_log_5_port, N_10);
  L1_add_30_aco_U5: iv110 PORT MAP (score_to_log_1_port, N_35);
  L1_add_30_aco_U4: iv110 PORT MAP (N_31, N_33);
  L1_add_30_aco_U3: iv110 PORT MAP (N_15, N_16);
  L1_add_30_aco_U2: iv110 PORT MAP (N_3, N_2);
  L1_U14: iv110 PORT MAP (N_26, N_30);
  L1_add_30_aco_U1: iv110 PORT MAP (N_6, N_7);
  L1_U12: iv110 PORT MAP (N_13, N_28);

END extracted;



