-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 3-Dec-13 12:04:02
-- Path: /home/epo3-user/EPO3/score/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Log_score IS

  SIGNAL N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8: STD_LOGIC;
  SIGNAL N_9, N_10, N_11, N_12, N_13, N_14, N_15, N_16: STD_LOGIC;
  SIGNAL N_17, N_18, N_19, N_20, N_21, N_22, N_23, N_24: STD_LOGIC;
  SIGNAL N_25, N_26, N_27, N_28: STD_LOGIC;
  SIGNAL score_to_log_6_port: STD_LOGIC;
  SIGNAL score_to_log_0_port: STD_LOGIC;
  SIGNAL score_to_log_1_port: STD_LOGIC;
  SIGNAL score_to_log_2_port: STD_LOGIC;
  SIGNAL score_to_log_3_port: STD_LOGIC;
  SIGNAL score_to_log_4_port: STD_LOGIC;
  SIGNAL score_to_log_5_port: STD_LOGIC;

  SIGNAL output_int: STD_LOGIC_VECTOR(7 DOWNTO 0);

BEGIN

  output <= output_int;


  L1_U48: ex210 PORT MAP (score_to_log_0_port, increase, N_21);
  L1_U30: ex210 PORT MAP (N_17, N_16, N_12);
  L1_U39: ex210 PORT MAP (score_to_log_3_port, N_15, N_13);
  L1_U28: ex210 PORT MAP (output_int(7), N_18, N_11);
  L1_U33: ex210 PORT MAP (score_to_log_5_port, N_7, N_14);
  L1_U37: ex210 PORT MAP (score_to_log_4_port, N_3, N_19);
  L1_U45: ex210 PORT MAP (N_6, N_8, N_10);
  L1_U43: ex210 PORT MAP (score_to_log_2_port, N_9, N_1);
  L1_score_reg_4_inst: dfr11 PORT MAP (N_20, rst, clk, score_to_log_4_port);
  L1_score_reg_0_inst: dfr11 PORT MAP (N_21, rst, clk, score_to_log_0_port);
  L1_score_reg_6_inst: dfr11 PORT MAP (N_12, rst, clk, score_to_log_6_port);
  L1_score_reg_3_inst: dfr11 PORT MAP (N_13, rst, clk, score_to_log_3_port);
  L1_score_reg_1_inst: dfr11 PORT MAP (N_10, rst, clk, score_to_log_1_port);
  L1_score_reg_7_inst: dfr11 PORT MAP (N_11, rst, clk, output_int(7));
  L1_score_reg_5_inst: dfr11 PORT MAP (N_14, rst, clk, score_to_log_5_port);
  L1_score_reg_2_inst: dfr11 PORT MAP (N_1, rst, clk, score_to_log_2_port);
  L1_U35: na310 PORT MAP (score_to_log_4_port, score_to_log_3_port, N_15, N_5);
  L1_U41: na310 PORT MAP (score_to_log_1_port, score_to_log_0_port, score_to_log_2_port, N_2);
  L2_U27: na210 PORT MAP (N_26, N_28, output_int(5));
  L2_U24: na210 PORT MAP (N_27, N_25, output_int(3));
  L1_U31: na210 PORT MAP (score_to_log_5_port, N_7, N_16);
  L1_U38: na210 PORT MAP (N_15, score_to_log_3_port, N_3);
  L1_U46: na210 PORT MAP (increase, score_to_log_0_port, N_8);
  L2_U26: no210 PORT MAP (score_to_log_4_port, output_int(5), N_27);
  L2_U23: no210 PORT MAP (score_to_log_2_port, output_int(3), N_24);
  L2_U21: no210 PORT MAP (output_int(2), score_to_log_1_port, N_23);
  L2_U19: no210 PORT MAP (score_to_log_0_port, output_int(1), N_22);
  L2_U29: no210 PORT MAP (score_to_log_6_port, output_int(7), N_26);
  L1_U29: no210 PORT MAP (N_16, N_17, N_18);
  L1_U40: no210 PORT MAP (N_4, N_2, N_15);
  L1_U44: no210 PORT MAP (N_6, N_8, N_9);
  L2_U28: iv110 PORT MAP (score_to_log_5_port, N_28);
  L2_U17: iv110 PORT MAP (N_27, output_int(4));
  L2_U25: iv110 PORT MAP (score_to_log_3_port, N_25);
  L2_U22: iv110 PORT MAP (N_24, output_int(2));
  L2_U18: iv110 PORT MAP (N_22, output_int(0));
  L2_U20: iv110 PORT MAP (N_23, output_int(1));
  L2_U16: iv110 PORT MAP (N_26, output_int(6));
  L1_U36: iv110 PORT MAP (N_19, N_20);
  L1_U32: iv110 PORT MAP (score_to_log_6_port, N_17);
  L1_U42: iv110 PORT MAP (increase, N_4);
  L1_U34: iv110 PORT MAP (N_5, N_7);
  L1_U47: iv110 PORT MAP (score_to_log_1_port, N_6);

END extracted;



