-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 24-Nov-13 15:51:44
-- Path: /home/epo3-user/score/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Score IS

  SIGNAL add_30_aco_n8: STD_LOGIC;
  SIGNAL n8: STD_LOGIC;
  SIGNAL add_30_aco_n10: STD_LOGIC;
  SIGNAL add_30_aco_n13: STD_LOGIC;
  SIGNAL add_30_aco_n7: STD_LOGIC;
  SIGNAL add_30_aco_n6: STD_LOGIC;
  SIGNAL add_30_aco_n14: STD_LOGIC;
  SIGNAL add_30_aco_n11: STD_LOGIC;
  SIGNAL add_30_aco_n15: STD_LOGIC;
  SIGNAL add_30_aco_n16: STD_LOGIC;
  SIGNAL add_30_aco_n3: STD_LOGIC;
  SIGNAL next_score_3_port: STD_LOGIC;
  SIGNAL next_score_2_port: STD_LOGIC;
  SIGNAL n11: STD_LOGIC;
  SIGNAL add_30_aco_n18: STD_LOGIC;
  SIGNAL n10: STD_LOGIC;
  SIGNAL add_30_aco_n12: STD_LOGIC;
  SIGNAL next_score_4_port: STD_LOGIC;
  SIGNAL next_score_0_port: STD_LOGIC;
  SIGNAL n13: STD_LOGIC;
  SIGNAL next_score_5_port: STD_LOGIC;
  SIGNAL add_30_aco_n9: STD_LOGIC;
  SIGNAL next_score_6_port: STD_LOGIC;
  SIGNAL next_score_7_port: STD_LOGIC;
  SIGNAL add_30_aco_n19: STD_LOGIC;
  SIGNAL add_30_aco_n17: STD_LOGIC;
  SIGNAL next_score_1_port: STD_LOGIC;
  SIGNAL add_30_aco_n4: STD_LOGIC;
  SIGNAL add_30_aco_n23: STD_LOGIC;
  SIGNAL add_30_aco_n20: STD_LOGIC;
  SIGNAL add_30_aco_n5: STD_LOGIC;
  SIGNAL add_30_aco_n22: STD_LOGIC;
  SIGNAL add_30_aco_n21: STD_LOGIC;
  SIGNAL n9: STD_LOGIC;
  SIGNAL n12: STD_LOGIC;

  SIGNAL output_int: STD_LOGIC_VECTOR(7 DOWNTO 0);

BEGIN

  output <= output_int;


  U15: na210 PORT MAP (increase_value(0), increase, n10);
  U13: na210 PORT MAP (increase_value(1), increase, n9);
  U11: na210 PORT MAP (increase_value(2), increase, n8);
  add_30_aco_U8: na210 PORT MAP (add_30_aco_n9, output_int(6), add_30_aco_n8);
  add_30_aco_U17: na210 PORT MAP (n11, add_30_aco_n3, add_30_aco_n15);
  add_30_aco_U16: na210 PORT MAP (add_30_aco_n14, add_30_aco_n15, add_30_aco_n11);
  add_30_aco_U19: na210 PORT MAP (output_int(2), add_30_aco_n17, add_30_aco_n14);
  add_30_aco_U14: na210 PORT MAP (add_30_aco_n11, output_int(3), add_30_aco_n13);
  add_30_aco_U28: na210 PORT MAP (n13, output_int(0), add_30_aco_n22);
  add_30_aco_U25: na210 PORT MAP (output_int(1), add_30_aco_n4, add_30_aco_n19);
  add_30_aco_U22: na210 PORT MAP (add_30_aco_n19, add_30_aco_n20, add_30_aco_n17);
  add_30_aco_U24: na210 PORT MAP (add_30_aco_n5, add_30_aco_n22, add_30_aco_n21);
  add_30_aco_U23: na210 PORT MAP (n12, add_30_aco_n21, add_30_aco_n20);
  U10: iv110 PORT MAP (n8, n11);
  add_30_aco_U3: iv110 PORT MAP (add_30_aco_n16, add_30_aco_n3);
  add_30_aco_U2: iv110 PORT MAP (add_30_aco_n7, next_score_7_port);
  add_30_aco_U6: iv110 PORT MAP (output_int(5), add_30_aco_n6);
  add_30_aco_U1: iv110 PORT MAP (add_30_aco_n12, next_score_4_port);
  U14: iv110 PORT MAP (n10, n13);
  add_30_aco_U5: iv110 PORT MAP (output_int(1), add_30_aco_n5);
  add_30_aco_U4: iv110 PORT MAP (add_30_aco_n22, add_30_aco_n4);
  U12: iv110 PORT MAP (n9, n12);
  add_30_aco_U10: no210 PORT MAP (add_30_aco_n6, add_30_aco_n10, add_30_aco_n9);
  add_30_aco_U18: no210 PORT MAP (add_30_aco_n17, output_int(2), add_30_aco_n16);
  add_30_aco_U11: ex210 PORT MAP (add_30_aco_n6, add_30_aco_n10, next_score_5_port);
  add_30_aco_U7: ex210 PORT MAP (output_int(7), add_30_aco_n8, add_30_aco_n7);
  add_30_aco_U13: ex210 PORT MAP (output_int(4), add_30_aco_n13, add_30_aco_n12);
  add_30_aco_U15: ex210 PORT MAP (output_int(3), add_30_aco_n11, next_score_3_port);
  add_30_aco_U29: ex210 PORT MAP (n13, output_int(0), next_score_0_port);
  add_30_aco_U20: ex210 PORT MAP (add_30_aco_n17, add_30_aco_n18, next_score_2_port);
  add_30_aco_U21: ex210 PORT MAP (n11, output_int(2), add_30_aco_n18);
  add_30_aco_U9: ex210 PORT MAP (output_int(6), add_30_aco_n9, next_score_6_port);
  add_30_aco_U26: ex210 PORT MAP (add_30_aco_n4, add_30_aco_n23, next_score_1_port);
  add_30_aco_U27: ex210 PORT MAP (n12, output_int(1), add_30_aco_n23);
  score_reg_2_inst: dfr11 PORT MAP (next_score_2_port, rst, clk, output_int(2));
  score_reg_4_inst: dfr11 PORT MAP (next_score_4_port, rst, clk, output_int(4));
  score_reg_3_inst: dfr11 PORT MAP (next_score_3_port, rst, clk, output_int(3));
  score_reg_0_inst: dfr11 PORT MAP (next_score_0_port, rst, clk, output_int(0));
  score_reg_1_inst: dfr11 PORT MAP (next_score_1_port, rst, clk, output_int(1));
  score_reg_5_inst: dfr11 PORT MAP (next_score_5_port, rst, clk, output_int(5));
  score_reg_6_inst: dfr11 PORT MAP (next_score_6_port, rst, clk, output_int(6));
  score_reg_7_inst: dfr11 PORT MAP (next_score_7_port, rst, clk, output_int(7));
  add_30_aco_U12: na310 PORT MAP (output_int(3), add_30_aco_n11, output_int(4), add_30_aco_n10);

END extracted;



