-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 3-Dec-13 11:39:15
-- Path: /home/epo3-user/EPO3/score/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Score IS

  SIGNAL next_score_2_port: STD_LOGIC;
  SIGNAL n27: STD_LOGIC;
  SIGNAL n25: STD_LOGIC;
  SIGNAL n26: STD_LOGIC;
  SIGNAL n22: STD_LOGIC;
  SIGNAL n29: STD_LOGIC;
  SIGNAL n21: STD_LOGIC;
  SIGNAL n30: STD_LOGIC;
  SIGNAL n28: STD_LOGIC;
  SIGNAL next_score_1_port: STD_LOGIC;
  SIGNAL next_score_7_port: STD_LOGIC;
  SIGNAL next_score_6_port: STD_LOGIC;
  SIGNAL next_score_3_port: STD_LOGIC;
  SIGNAL next_score_5_port: STD_LOGIC;
  SIGNAL n23: STD_LOGIC;
  SIGNAL n19: STD_LOGIC;
  SIGNAL n20: STD_LOGIC;
  SIGNAL n18: STD_LOGIC;
  SIGNAL n24: STD_LOGIC;
  SIGNAL next_score_4_port: STD_LOGIC;
  SIGNAL next_score_0_port: STD_LOGIC;

  SIGNAL output_int: STD_LOGIC_VECTOR(7 DOWNTO 0);

BEGIN

  output <= output_int;


  U48: ex210 PORT MAP (output_int(0), increase, next_score_0_port);
  U30: ex210 PORT MAP (n20, n19, next_score_6_port);
  U39: ex210 PORT MAP (output_int(3), n23, next_score_3_port);
  U28: ex210 PORT MAP (output_int(7), n18, next_score_7_port);
  U33: ex210 PORT MAP (output_int(5), n21, next_score_5_port);
  U37: ex210 PORT MAP (output_int(4), n25, n24);
  U45: ex210 PORT MAP (n29, n30, next_score_1_port);
  U43: ex210 PORT MAP (output_int(2), n28, next_score_2_port);
  U36: iv110 PORT MAP (n24, next_score_4_port);
  U32: iv110 PORT MAP (output_int(6), n20);
  U42: iv110 PORT MAP (increase, n26);
  U34: iv110 PORT MAP (n22, n21);
  U47: iv110 PORT MAP (output_int(1), n29);
  score_reg_4_inst: dfr11 PORT MAP (next_score_4_port, rst, clk, output_int(4));
  score_reg_0_inst: dfr11 PORT MAP (next_score_0_port, rst, clk, output_int(0));
  score_reg_6_inst: dfr11 PORT MAP (next_score_6_port, rst, clk, output_int(6));
  score_reg_3_inst: dfr11 PORT MAP (next_score_3_port, rst, clk, output_int(3));
  score_reg_1_inst: dfr11 PORT MAP (next_score_1_port, rst, clk, output_int(1));
  score_reg_7_inst: dfr11 PORT MAP (next_score_7_port, rst, clk, output_int(7));
  score_reg_5_inst: dfr11 PORT MAP (next_score_5_port, rst, clk, output_int(5));
  score_reg_2_inst: dfr11 PORT MAP (next_score_2_port, rst, clk, output_int(2));
  U29: no210 PORT MAP (n19, n20, n18);
  U40: no210 PORT MAP (n26, n27, n23);
  U44: no210 PORT MAP (n29, n30, n28);
  U35: na310 PORT MAP (output_int(4), output_int(3), n23, n22);
  U41: na310 PORT MAP (output_int(1), output_int(0), output_int(2), n27);
  U31: na210 PORT MAP (output_int(5), n21, n19);
  U38: na210 PORT MAP (n23, output_int(3), n25);
  U46: na210 PORT MAP (increase, output_int(0), n30);

END extracted;



