1.000000e-10  ( clk ) ( rst ) ( mask_7_0_7 ) ( mask_7_0_6 ) ( mask_7_0_5 ) ( mask_7_0_4 ) ( mask_7_0_3 ) ( mask_7_0_2 ) ( mask_7_0_1 ) ( mask_7_0_0 ) ( mask_select_1_0_1 ) ( mask_select_1_0_0 ) ( x_2_0_2 ) ( x_2_0_1 ) ( x_2_0_0 ) ( y_3_0_3 ) ( y_3_0_2 ) ( y_3_0_1 ) ( y_3_0_0 ) ( rot_1_0_1 ) ( rot_1_0_0 ) ( piece_type_2_0_2 ) ( piece_type_2_0_1 ) ( piece_type_2_0_0 ) ( next_piece ) ( ready ) ( error_side ) ( error_bot ) ( start ) ( rom_addr_6_0_6 ) ( rom_addr_6_0_5 ) ( rom_addr_6_0_4 ) ( rom_addr_6_0_3 ) ( rom_addr_6_0_2 ) ( rom_addr_6_0_1 ) ( rom_addr_6_0_0 ) ( rom_data_3_0_3 ) ( rom_data_3_0_2 ) ( rom_data_3_0_1 ) ( rom_data_3_0_0 )
              0hhlhhllhhllhhhlhlhllhlhhlxllllhhlhlhhlll
              0hhlhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            100lhlhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            200hhlhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            300lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            400hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            500lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            600hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            700lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            800hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
            900lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1000hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1100lllhhllhhllhhhlhlhllhlhhllllhlhhlhlhhlll
           1200hllhhllhhllhhhlhlhllhlhhllllhlhhlhlhhlll
           1300lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1400hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1500lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1600hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1700lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1800hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1818hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           1900lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2000hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2100lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2200hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2300lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2400hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2419hllhhllhhllhhhlhlhllhlhhlhllllhhlhlhhlll
           2500lllhhllhhllhhhlhlhllhlhhlhllllhhlhlhhlll
           2600hllhhllhhllhhhlhlhllhlhhlhllllhhlhlhhlll
           2618hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2700lllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2800hllhhllhhllhhhlhlhllhlhhllllllhhlhlhhlll
           2900lllhhllhhlhlhhlhlhllhlhhllllllhhlhhlhlll
           3000hllhhllhhlhlhhlhlhllhlhhllllllhhlhhlhlll
           3100lllhhllhhlhlhhlhlhllhlhhllllhlhhlhhlhlll
           3200hllhhllhhlhlhhlhlhllhlhhllllhlhhlhhlhlll
           3300lllhhllhhlhlhhlhlhllhlhhllllllhhlhhlhlll
           3400hllhhllhhlhlhhlhlhllhlhhllllllhhlhhlhlll
           3500lllhhllhhlhlhhlhlhllhlhhllllllhhlhhlhllh
           3502lllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           3600hllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           3700lllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           3800hllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           3818hllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           3900lllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4000hllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4100lllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4200hllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4300lllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4400hllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4419hllhhllhhhhlhhlhlhllhlhhlhllllhhlhhlhllh
           4500lllhhllhhhhlhhlhlhllhlhhlhllllhhlhhlhllh
           4600hllhhllhhhhlhhlhlhllhlhhlhllllhhlhhlhllh
           4618hllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4700lllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4800hllhhllhhhhlhhlhlhllhlhhllllllhhlhhlhllh
           4900lllhhllhhhhhhhlhlhllhlhhllllllhhlhhhhllh
           5000hllhhllhhhhhhhlhlhllhlhhllllllhhlhhhhllh
           5100lllhhllhhhhhhhlhlhllhlhhllllhlhhlhhhhllh
           5200hllhhllhhhhhhhlhlhllhlhhllllhlhhlhhhhllh
           5300lllhhllhhhhhhhlhlhllhlhhllllllhhlhhhhllh
           5400hllhhllhhhhhhhlhlhllhlhhllllllhhlhhhhllh
           5500lllhhllhhhhhhhlhlhllhlhhllllllhhlhhhhlhl
           5502lllhhllhhlhhhhlhlhllhlhhllllllhhlhhhhlhl
           5508lllhhlllhlhhhhlhlhllhlhhllllllhhlhhhhlhl
           5510lllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           5600hllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           5700lllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           5800hllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           5818hllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           5826hllhhlllllhhhhlhlhllhlhhllhlllhhlhhhhlhl
           5900lllhhlllllhhhhlhlhllhlhhllhlllhhlhhhhlhl
           6000hllhhlllllhhhhlhlhllhlhhllhlllhhlhhhhlhl
           6020hllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6100lllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6200hllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6300lllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6400hllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6500lllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6600hllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6700lllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6800hllhhlllllhhhhlhlhllhlhhllllllhhlhhhhlhl
           6900lllhhlllllllhhlhlhllhlhhllllllhhlhllhlhl
           7000hllhhlllllllhhlhlhllhlhhllllllhhlhllhlhl
           7100lllhhlllllllhhlhlhllhlhhllllhlhhlhllhlhl
           7200hllhhlllllllhhlhlhllhlhhllllhlhhlhllhlhl
           7300lllhhlllllllhhlhlhllhlhhllllllhhlhllhlhl
           7400hllhhlllllllhhlhlhllhlhhllllllhhlhllhlhl
           7500lllhhlllllllhhlhlhllhlhhllllllhhlhllhlhh
           7502lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           7600hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           7700lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           7800hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           7818hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           7826hllhhllllhllhhlhlhllhlhhllhlllhhlhllhlhh
           7900lllhhllllhllhhlhlhllhlhhllhlllhhlhllhlhh
           8000hllhhllllhllhhlhlhllhlhhllhlllhhlhllhlhh
           8020hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8100lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8200hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8300lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8400hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8500lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8600hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8700lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8800hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           8900lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9000hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9100lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9200hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9300lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9400hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9500lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9600hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9700lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9800hllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9900lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
           9999lllhhllllhllhhlhlhllhlhhllllllhhlhllhlhh
